### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [PaperMtn/slack-watchman#33]
Version 3.0.7

Running  sudo slack-watchman --pii --timeframe a
```
Importing rules...
40 rules loaded
Searching PII/Personal Data
Searching for posts containing Drivers Licence Numbers (UK)
'NoneType' object has no attribute 'get'
```

Running sudo slack-watchman --financial --timeframe a
```
Importing rules...
40 rules loaded
Searching financial data
Searching for posts containing IBAN Numbers
'NoneType' object has no attribute 'get
```

Running sudo slack-watchman --tokens --timeframe a
```
Importing rules...
40 rules loaded
Searching tokens
Searching for posts containing Client Secrets
'NoneType' object has no attribute 'get'
```

Any Ideas on how to fix?

**Comment by PaperMtn** [comment]
I _think_ this is a really stupid bug where some results are being searched without any checks to see if they exist. I will have a look.

**Comment by Phil-ThePower-Pearce** [comment]
I will also mention incase its related. That I was unable to set the search:read permission in slack as it wasnt available.

**Comment by PaperMtn** [comment]
Ok, you need to create an API token for user scope, and not bot scope. `search:read` only works with a user scope.

Can you create the API token under a user scope and try again? This error may be because the token you have passed doesn't have permissions.

**Comment by PaperMtn** [comment]
I have tested this out, and it is the missing API scope. The latest version that I have just released checks for missing scopes and returns in the error which one is missing, but I am sure that what you need to do is use a user token and add the scope `search:read`

**Comment by Phil-ThePower-Pearce** [comment]
Ok, I can do but I was  suggest following this: 
`you create this app and authorise it using a service account, otherwise the app will have access to your private channels and chats`
I dont want this app to access private channels and chats.  Will making this a user scope allow this?

**Comment by Phil-ThePower-Pearce** [comment]
I did as you said
sudo slack-watchman --tokens --timeframe a

```
Searching for GCP Service Account Files
Slack API rate limit reached - cooling off
Slack API rate limit reached - cooling off
Slack API rate limit reached - cooling off
HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/search.files?query=after%3A1920-01-14+%22.json%22&pretty=1&count=100&page=415 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f43028d79a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
'NoneType' object has no attribute 'json'

```

**Comment by PaperMtn** [comment]
Is this still an issue? The other issue you raised suggested that this may be sorted?

**Comment by Phil-ThePower-Pearce** [comment]
I have to admit, its still an issue. Ive just disabled the check so I could progress

**Comment by PaperMtn** [comment]
If you check out the latest version, i've added some extension handling that I think will catch this
